### ISSUE TITLE
Setting AllUniteId and AllUniteKey in the AlluniteSDK.initSdk function 

### ISSUE THREAD

**Issue by ddennis** [allunite/cordova-sdk#2]
Being able to set the AllUniteId and AllUniteKey in the AlluniteSDK.initSdk function, would be desirable. Since this would eliminate the need to change AlluniteSdkConfig.plist and the Android project manifest file.

A standard workflow when working with cordova is to sometime remove the IOS or Android platform and then add it again to fix problems when building the project. 

If manually changing the  p-list and the android manifest is required these changes will need to be applied everytime a platform is removed and re-added.

**Comment by Tuccro** [comment]
Now you can set up AllUniteId and AllUniteKey at plugin adding using parameters.
