### ISSUE TITLE
Adding intent filter and CFBundleURLSchemes  using Custom-URL-scheme plugin

### ISSUE THREAD

**Issue by ddennis** [allunite/cordova-sdk#3]
As mentioned in another issue, it's not desirable to manually have to make changes to Android manifest or p-list info. 

Using https://github.com/EddyVerbruggen/Custom-URL-scheme to handle setting a URI Scheme seems to work great for both android and IOS. Setting the correct intent-filter and CFBundleURLSchemes

**Comment by YuraKr** [comment]
Fix in plugin version 1.0.4 (android & ios)
Example:
cordova plugin add https://github.com/allunite/cordova-sdk --variable ACCOUNT_ID=your_id --variable ACCOUNT_KEY=your_key --variable URI_SCHEME=your_scheme

**Comment by ddennis** [comment]
Thank you very much
