### ISSUE TITLE
reinstalling plugin

### ISSUE THREAD

**Issue by ddennis** [allunite/cordova-sdk#4]
When trying to reinstall the plugin, to get the latest version. I have encountered this error:

     Error: Failed to fetch plugin https://github.com/allunite/cordova-sdk via registry.
     Probably this is either a connection problem, or plugin spec is incorrect.
     Check your connection and plugin name/version/URL.
     Failed to get absolute path to installed module

I tried forking the project and bumping the version number, which might have fixed it. 

This could have something to do with fetching the plugin from npm and the "npm cache".
But i am not sure!

**Comment by ddennis** [comment]
You will need to also update the package.json, which is the one generated by npm

**Comment by alexkalner** [comment]
Thank you Dennis, it will be done.

**Comment by ddennis** [comment]
I am on Windows 8.1
Cordova v7.0.1
npm -  v4.0.3
node - v6.9.1

Hmm - i still get the same error when trying to reinstall the plugin. Only solutions is to clone the repo and install it from local file system. 

[I have found this](https://ourcodeworld.com/articles/read/455/cordova-error-failed-to-fetch-plugin-npm-not-being-able-to-find-a-package-json-in-a-package-you-are-trying-to-install)

Looking at your package.json, you do have some reference to another repo: "url": "git+https://github.com/YuraKr/cordova-sdk.git"
