### ISSUE TITLE
Android initSdk - callback never called.

### ISSUE THREAD

**Issue by ddennis** [allunite/cordova-sdk#5]
**On Android**
I am on Windows 8.1
Cordova v7.0.1
npm - v4.0.3
node - v6.9.1

I am seeing this issue on **Android** in both the demo project and the implementation in ReklameBingo. Neither the success or failure callback is called.

    AlluniteSDK.initSdk(function success(message){
     console.log (" AllUniteService.js > success init = " , msg);
     }, function failure(msg){
     console.log (" AllUniteService.js > failed init = " , msg);
     });

**Comment by Tuccro** [comment]
Fixed
